server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:9090/eureka
  instance:
    preferIpAddress: true

spring:
  application:
    name: external-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: authservice
          uri: lb://authservice
          predicates:
            - Path=/auth/**

        - id: ignoreusersearch
          uri: no://op
          predicates:
            - Path=/users/search
          filters:
            - SetStatus=403

        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/users/**
          filters:
            - TokenFilter

        - id: productservice
          uri: lb://productservice
          predicates:
            - Path=/products/**
          filters:
            - TokenFilter

        - id: orderservice
          uri: lb://orderservice
          predicates:
            - Path=/orders/**
          filters:
            - TokenFilter

        - id: eventservice
          uri: lb://eventservice
          predicates:
            - Path=/events/**
          filters:
            - TokenFilter
