version: '2.1'
services:

  ###################
  ##    BACKEND    ##
  ###################
  
  eventservice:
    build: .
    container_name: eventservice
    image: eventservice
    ports:
      - 8085:8085
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8085/actuator/health" ]
      interval: 5s
      timeout: 1s
      retries: 10
