version: "3"
services:
    authweb:
        build:
            context: ./
            args:
                - GITHUB_TOKEN=${GITHUB_TOKEN}
        container_name: authweb
        ports:
            - 7075:80
