version: '2.1'
services:

  ###################
  ##    GATEWAY    ##
  ###################
  
  external-gateway:
    build: .
    container_name: external-gateway
    image: external-gateway
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - PROFILE=docker-external
      - ALLOWED_URL=http://localhost:7070
      - JVM_OPTS=-Xmx512m -Xms512m
    ports:
      - 8080:8080
      
  internal-gateway:
    build: .
    container_name: internal-gateway
    image: internal-gateway
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - PROFILE=docker-internal
      - JVM_OPTS=-Xmx512m -Xms512m
    ports:
      - 8070:8080

