apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: authservice
  name: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: authservice
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: authservice
    spec:
      containers:
        - env:
            - name: JVM_OPTS
              value: -Xmx512m -Xms512m
            - name: SECRET_KEY
              value: 1jcryR3Lsf
          image: authservice
          imagePullPolicy: IfNotPresent
          name: authservice
          ports:
            - containerPort: 8082
          resources: {}
      restartPolicy: Always
status: {}
