version: '2.1'
services:

  ###################
  ##    BACKEND    ##
  ###################
      
  authservice:
    build: .
    container_name: authservice
    image: authservice
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - JVM_OPTS=-Xmx512m -Xms512m
    ports:
      - 8082:8082
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 5s
      timeout: 1s
      retries: 10
      