server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:9090/eureka
  instance:
    preferIpAddress: true

kafka:
  bootstrapServer: kafka:9092
  consumerGroup: orderservice
  topics:
    product: product

spring:
  application:
    name: orderservice
  redis:
    host: order-redis
    port: 6379
    database: 0
    timeout: 60000
    defalt-ttl-in-mins: 5
  datasource:
    url: jdbc:postgresql://order-db:5432/boilerplate
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

flyway:
  user: postgres
  password: admin
  url: jdbc:postgresql://order-db:5432/boilerplate