version: "2.1"
services:
  ###################
  ##    BACKEND    ##
  ###################

  user-db:
    image: "postgres"
    container_name: user-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=boilerplate
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 1s
      retries: 10

  userservice:
    build: .
    container_name: userservice
    image: userservice
    environment:
      - JVM_OPTS=-Xmx512m -Xms512m
    ports:
      - 8081:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 5s
      timeout: 1s
      retries: 10
