apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: eventservice
  name: eventservice
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8085
  selector:
    io.kompose.service: eventservice
status:
  loadBalancer: {}
