apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: external-gateway
  name: external-gateway
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: external-gateway
status:
  loadBalancer: {}
