apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: internal-gateway
  name: internal-gateway
spec:
  ports:
    - name: "8070"
      port: 8070
      targetPort: 8080
  selector:
    io.kompose.service: internal-gateway
status:
  loadBalancer: {}
