apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: product-db
  name: product-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product-db
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: product-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: boilerplate
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          name: product-db
          resources: {}
      restartPolicy: Always
status: {}
