apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: productservice
  name: productservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: productservice
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: productservice
    spec:
      containers:
        - env:
            - name: JVM_OPTS
              value: -Xmx512m -Xms512m
          image: productservice
          imagePullPolicy: IfNotPresent
          name: productservice
          ports:
            - containerPort: 8083
          resources: {}
      restartPolicy: Always
status: {}
