apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: productservice
  name: productservice
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
  selector:
    io.kompose.service: productservice
status:
  loadBalancer: {}
