version: "3"

services:
    orderweb:
        build:
            context: ./
            args:
                - GITHUB_TOKEN=${GITHUB_TOKEN}
        container_name: orderweb
        ports:
            - 7072:80
