version: "3"

services:
    eventweb:
        build:
            context: ./
            args:
                - GITHUB_TOKEN=${GITHUB_TOKEN}
        container_name: eventweb
        ports:
            - 7071:80
