apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: authweb
  name: authweb
spec:
  ports:
    - name: "7075"
      port: 7075
      targetPort: 80
  selector:
    io.kompose.service: authweb
status:
  loadBalancer: {}
