server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka
  instance:
    preferIpAddress: true

kafka:
  bootstrapServer: localhost:9092
  consumerGroup: eventservice
  topics: product

spring:
  application:
    name: eventservice

elasticsearch:
  host: localhost:9200
