version: '2.1'
services:

  ###################
  ##    BACKEND    ##
  ###################
  
  eureka:
    build: .
    container_name: eureka
    image: eureka
    environment:
      - JVM_OPTS=-Xmx512m -Xms512m
    ports:
      - 9090:9090
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/eureka/apps" ]
      interval: 5s
      timeout: 1s
      retries: 10
   