apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: userservice
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: userservice
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: userservice
    spec:
      containers:
        - env:
            - name: JVM_OPTS
              value: -Xmx512m -Xms512m
          image: userservice
          imagePullPolicy: IfNotPresent
          name: userservice
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
