apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: userweb
  name: userweb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: userweb
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: userweb
    spec:
      containers:
        - image: userweb
          imagePullPolicy: IfNotPresent
          name: userweb
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
