version: "3"

services:
    userweb:
        build:
            context: ./
            args:
                - GITHUB_TOKEN=${GITHUB_TOKEN}
        container_name: userweb
        ports:
            - 7074:80
