apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: orderservice
  name: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orderservice
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: orderservice
    spec:
      containers:
        - env:
            - name: JVM_OPTS
              value: -Xmx512m -Xms512m
          image: orderservice
          imagePullPolicy: IfNotPresent
          name: orderservice
          ports:
            - containerPort: 8084
          resources: {}
      restartPolicy: Always
status: {}
