apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: userweb
  name: userweb
spec:
  ports:
    - name: "7074"
      port: 7074
      targetPort: 80
  selector:
    io.kompose.service: userweb
status:
  loadBalancer: {}
