version: "2.1"
services:
  
  ###################
  ##    BACKEND    ##
  ###################

  shellsystem:
    extends:
      file: ./packages/system/shellsystem/docker-compose.yml
      service: shellsystem
    depends_on:
      eureka:
        condition: service_healthy

  authservice:
    extends:
      file: ./packages/service/authservice/docker-compose.yml
      service: authservice
    depends_on:
      eureka:
        condition: service_healthy

  eureka:
    extends:
      file: ./packages/service/eurekaserver/docker-compose.yml
      service: eureka

  eventservice:
    extends:
      file: ./packages/service/eventservice/docker-compose.yml
      service: eventservice
    depends_on:
      eureka:
        condition: service_healthy

  external-gateway:
    extends:
      file: ./packages/service/gatewayservice/docker-compose.yml
      service: external-gateway
    depends_on:
      eureka:
        condition: service_started
      userservice:
        condition: service_started
      authservice:
        condition: service_started
      productservice:
        condition: service_started
      orderservice:
        condition: service_started
      eventservice:
        condition: service_started

  internal-gateway:
    extends:
      file: ./packages/service/gatewayservice/docker-compose.yml
      service: internal-gateway
    depends_on:
      eureka:
        condition: service_started
      userservice:
        condition: service_started
      authservice:
        condition: service_started
      productservice:
        condition: service_started
      orderservice:
        condition: service_started
      eventservice:
        condition: service_started

  orderservice:
    extends:
      file: ./packages/service/orderservice/docker-compose.yml
      service: orderservice
    depends_on:
      eureka:
        condition: service_healthy
      order-db:
        condition: service_healthy
      order-redis:
        condition: service_healthy

  productservice:
    extends:
      file: ./packages/service/productservice/docker-compose.yml
      service: productservice
    depends_on:
      eureka:
        condition: service_healthy
      product-db:
        condition: service_healthy
      product-redis:
        condition: service_healthy

  userservice:
    extends:
      file: ./packages/service/userservice/docker-compose.yml
      service: userservice
    depends_on:
      eureka:
        condition: service_healthy
      user-db:
        condition: service_healthy
