name: utility-ci

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  test-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn test:service

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn test:e2e
